### ISSUE TITLE
Octave compatible?

### ISSUE THREAD

**Issue by stefano2734** [Prabhuram-K/MATLAB-CFD-code-for-transient-1D-heat-conduction-using-explicit-scheme#2]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info.
if unknown, untested with octave is also nice.
if no, it is also ok. Some commands are not compatible in octave.

**Comment by Prabhuram-K** [comment]
Untested with octave. I'd be interested to see the test results in Octave.
